const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { randomBytes, randomUUID } = require('node:crypto');
const { Pool } = require('pg');
const express = require('express');
const jwt = require('jsonwebtoken');
const { createLabRouter, validateMaster, pdfContent } = require('../routes/lab.routes');
const env = require('dotenv').parse(fs.readFileSync(path.join(__dirname,'../.env')));
const config = {host:env.DB_HOST,port:env.DB_PORT,user:env.DB_USER,password:env.DB_PASSWORD,database:env.DB_NAME,connectionTimeoutMillis:10000};
const schema = 'lab_test_'+randomBytes(8).toString('hex');
const owner = new Pool(config), db = new Pool({...config,options:`-c search_path=${schema}`,max:5});
process.env.JWT_SECRET = randomBytes(32).toString('hex');
let server, base;
async function request(url,method='GET',body,user=1) {
 const response=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(user?{Authorization:'Bearer '+jwt.sign({userId:user},process.env.JWT_SECRET)}:{})},...(body?{body:JSON.stringify(body)}:{})});
 if(response.headers.get('content-type')?.includes('application/pdf'))return {status:response.status,body:Buffer.from(await response.arrayBuffer()),headers:response.headers};
 return {status:response.status,body:await response.json()};
}
before(async()=>{
 assert.match(schema,/^lab_test_[a-f0-9]{16}$/);
 await owner.query(`CREATE SCHEMA ${schema}`);
 await db.query('CREATE TABLE users(id bigint PRIMARY KEY,name text,email text,isadmin boolean)');
 await db.query(fs.readFileSync(path.join(__dirname,'../migrations/006_lab_module.sql'),'utf8'));
 await db.query(`INSERT INTO users VALUES(1,'Admin','admin@example.invalid',true),(2,'Patient','patient@example.invalid',false),(3,'Other','other@example.invalid',false),(4,'Collector','collector@example.invalid',false),(5,'Lab','lab@example.invalid',false)`);
 const app=express();app.use(express.json({limit:'8mb'}));app.use('/lab',createLabRouter(db));
 server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});base=`http://127.0.0.1:${server.address().port}/lab`;
});
after(async()=>{
 if(server)await new Promise(resolve=>server.close(resolve));
 await db.end();assert.match(schema,/^lab_test_[a-f0-9]{16}$/);
 await owner.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await owner.end();
});
test('master validation and PDF upload validation reject malformed input',()=>{
 assert.throws(()=>validateMaster('constructor',{}),/Unknown/);
 assert.throws(()=>validateMaster('areas',{name:'Village',pincode:'xx',collection_fee:0}),/pincode/);
 assert.throws(()=>validateMaster('tests',{name:'CBC',kind:'test',price:-1}),/amount/);
 assert.throws(()=>pdfContent(Buffer.from('<html>not a report</html>').toString('base64')),/valid PDF/);
 assert.throws(()=>pdfContent('!@#$'),/PDF/);
});
test('lab workflow persists bookings, protects patient data, verifies samples and controls payments',async()=>{
 for(const route of ['/bookings','/admin/masters','/session'])assert.equal((await request(route,'GET',null,null)).status,401);
 assert.equal((await request('/admin/masters','GET',null,2)).status,403);
 assert.equal((await request('/catalog','GET',null,null)).status,200);
 const area=(await request('/admin/masters/areas','POST',{name:'Test Village',pincode:'110001',collection_fee:50})).body;
 const otherArea=(await request('/admin/masters/areas','POST',{name:'Other Village',pincode:'110002',collection_fee:50})).body;
 const lab=(await request('/admin/masters/laboratories','POST',{name:'Test Lab',phone:'9876543210',address:'Main Road'})).body;
 const collector=(await request('/admin/masters/collectors','POST',{name:'Collector',phone:'9876543211',area_id:area.id})).body;
 const wrongCollector=(await request('/admin/masters/collectors','POST',{name:'Other Collector',phone:'9876543212',area_id:otherArea.id})).body;
 const t=(await request('/admin/masters/tests','POST',{name:'CBC',kind:'test',price:300,sample_type:'Blood',turnaround_hours:24})).body;
 assert.ok(t.id);
 assert.equal((await request('/admin/access','POST',{user_id:4,collector_id:collector.id})).status,200);
 assert.equal((await request('/admin/access','POST',{user_id:5,laboratory_id:lab.id})).status,200);
 const payload={request_key:randomUUID(),patient_name:'Patient',phone:'9876543210',address:'House 1, Main Road',area_id:area.id,collection_at:new Date(Date.now()+86400000).toISOString(),test_ids:[t.id],total:1};
 const created=await Promise.all([request('/bookings','POST',payload,2),request('/bookings','POST',payload,2)]);
 assert.equal(created[0].status,201);assert.equal(created[1].body.id,created[0].body.id);
 const b=created[0].body;assert.equal(Number(b.total),350);
 assert.equal((await request('/bookings','GET',null,2)).body.length,1);
 assert.equal((await request('/bookings','GET',null,3)).body.length,0);
 assert.equal((await request(`/bookings/${b.id}/events`,'GET',null,3)).status,403);
 assert.equal((await request(`/bookings/${b.id}/report`,'GET',null,3)).status,403);
 const at=`/bookings/${b.id}`;
 assert.equal((await request(at+'/assign','POST',{collector_id:collector.id,laboratory_id:lab.id},2)).status,403);
 assert.equal((await request(at+'/assign','POST',{collector_id:wrongCollector.id,laboratory_id:lab.id})).status,400);
 assert.equal((await request(at+'/assign','POST',{collector_id:collector.id,laboratory_id:lab.id,collector_due:100,lab_due:200})).status,200);
 assert.equal((await request('/bookings','GET',null,4)).body.length,1);
 assert.equal((await request(at+'/status','POST',{status:'processing'},5)).status,409);
 assert.equal((await request(at+'/status','POST',{status:'collected',barcode:'wrong'},4)).status,400);
 assert.equal((await request(at+'/status','POST',{status:'collected',barcode:b.barcode},2)).status,403);
 assert.equal((await request(at+'/status','POST',{status:'collected',barcode:b.barcode},4)).status,200);
 assert.equal((await request(at+'/assign','POST',{collector_id:collector.id,laboratory_id:lab.id})).status,409);
 assert.equal((await request(at+'/status','POST',{status:'received',barcode:b.barcode},4)).status,403);
 assert.equal((await request(at+'/status','POST',{status:'received',barcode:b.barcode},5)).status,200);
 assert.equal((await request(at+'/status','POST',{status:'processing'},5)).status,200);
 assert.equal((await request(at+'/status','POST',{status:'report_ready'},5)).status,409);
 const pdf=Buffer.from('%PDF-1.4\n1 0 obj <</Type /Catalog>> endobj\n%%EOF');
 const report={filename:'report.pdf',content:pdf.toString('base64')};
 assert.equal((await request(at+'/report','PUT',report,4)).status,403);
 assert.equal((await request(at+'/report','PUT',report,5)).status,200);
 assert.equal((await request(at+'/report','GET',null,2)).status,403);
 assert.equal((await request(at+'/status','POST',{status:'report_ready'},5)).status,200);
 assert.deepEqual((await request(at+'/report','GET',null,2)).body,pdf);
 assert.equal((await request(at+'/report','GET',null,4)).status,403);
 assert.equal((await request(at+'/report','PUT',report,5)).status,409);
 assert.equal((await request(at+'/payment','POST',{paid_amount:350,note:'Cash receipt'},4)).status,403);
 assert.equal((await request(at+'/settle','POST',{party:'lab',note:'Transfer'})).status,409);
 assert.equal((await request(at+'/payment','POST',{paid_amount:351,note:'Cash receipt'})).status,400);
 assert.equal((await request(at+'/payment','POST',{paid_amount:350,note:'Cash receipt'})).status,200);
 assert.equal((await request(at+'/settle','POST',{party:'lab',note:'Bank transfer REF123'})).status,200);
 assert.equal((await request(at+'/settle','POST',{party:'lab',note:'Duplicate'})).status,409);
 assert.equal((await request(at+'/payment','POST',{paid_amount:0,note:'Refund'})).status,409);
 assert.ok((await request(at+'/events','GET',null,2)).body.some(e=>e.status==='report_ready'));
 await request('/admin/access/4','DELETE');assert.equal((await request('/bookings','GET',null,4)).body.length,0);
 assert.equal((await request('/bookings','POST',{...payload,request_key:randomUUID(),patient_user_id:3},2)).status,403);
 const adminBooking=await request('/bookings','POST',{...payload,request_key:randomUUID(),patient_user_id:3});
 assert.equal(adminBooking.status,201);
 assert.equal((await request('/bookings','GET',null,3)).body[0].id,adminBooking.body.id);
 const summary=await request('/admin/analytics');
 assert.equal(summary.body.summary.total,2);assert.equal(Number(summary.body.summary.cash_received),350);
 assert.equal(summary.body.tests[0].count,2);
 assert.equal((await request('/admin/analytics','GET',null,2)).status,403);
 const otherAt=`/bookings/${adminBooking.body.id}`;
 assert.equal((await request(otherAt+'/payment','POST',{paid_amount:50,note:'Deposit'})).status,200);
 assert.equal((await request(otherAt+'/status','POST',{status:'cancelled'},3)).status,409);
 assert.equal((await request(otherAt+'/payment','POST',{paid_amount:0,note:'Deposit refunded'})).status,200);
 assert.equal((await request(otherAt+'/status','POST',{status:'cancelled'},3)).status,200);
});
